/**
 * Standard Application Error Codes matching standard JSON error response:
 * { "error": { "code": "...", "message": "..." } }
 */
export const ERROR_CODES = {
  // 400 Bad Request / Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INVALID_DOMAIN: 'INVALID_DOMAIN',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  
  // 401 Unauthorized / 403 Forbidden
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ADMIN_INACTIVE: 'ADMIN_INACTIVE',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // 404 Not Found
  NOT_FOUND: 'NOT_FOUND',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  GALLERY_NOT_FOUND: 'GALLERY_NOT_FOUND',
  USERNAME_NOT_FOUND: 'USERNAME_NOT_FOUND',

  // 429 Rate Limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // 500 Internal Server Error
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  BLOB_STORAGE_ERROR: 'BLOB_STORAGE_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
